spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

#logging:
#  level:
#    org:
#      elasticsearch: trace
#      apache:
#        http: trace

---

spring:
  profiles: cloud
  jpa:
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        default_schema: public
        ddl-auto: create-drop
    open-in-view: false
  datasource:
    url: jdbc:yugabytedb://localhost:5433/yugabyte?load-balance=true
    username: yugabyte
    password:
    driver-class-name: com.yugabyte.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: false